### ISSUE TITLE
Question on dpu-lldb

### ISSUE THREAD

**Issue by alex1230608** [upmem/dpu_demo#11]
Hi,
First of all, I am sorry if this is not a good place to ask this. 

I encountered an error using dpu-lldb.
I follow the sdk documentation to write the helloworld.c program for DPU, compile it, and run it in dpu-lldb.
The package I use is the deb package for SDK version 2020.3.0 on my own Ubuntu 18.04 server (no DPUs installed).

However, when I execute `process launch`, I got the following error:
```
error: process launch failed: 'A' packet returned an error: 8
```

Hope you can help me identify the problems.
Thank you!

Sincerely,
Kuo-Feng

**Comment by ghost** [comment]
Dear Kuo-Feng,

By default the toolchain is looking for hardware DPU (or FPGA). As you do not have it on your server, `dpu-lldb` is failling.
To force the toolchain to target the simulator, you need to set the following environment variable in your system:
```
UPMEM_PROFILE_BASE="backend=simulator"
```

Regards,
Romaric

**Comment by ghost** [comment]
For other questions not directly related to `dpu_demo` please send a email to support@upmem.com

Thanks,
Romaric

**Comment by alex1230608** [comment]
Thank you, Romaric.
Adding the environment variable works! I will use the email address if I have further questions.

Sincerely,
Kuo-Feng
